# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
github: [metadata]
paginate: 7 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: qsnotepad
google_analytics: UA-68629572-1
encoding: utf-8
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Bryan
      description: quick notes
author:
  name: Bryan Nguyễn
  email: hongquy@inspectorio.com
  bio: Full Stack-Over-Flow Data Science
  linkedin: hongquy
  github: dongchirua
  instagram: dongchirua
  #facebook: hquy.nguyen
  #500px: quynguyen4
  #googleplus: +NguyenHongQuydongchirua
  scholar: TmzXDGsAAAAJ
  stack: 1432142
  email_md5: 1f666b3428d24513c8376b9be1463d8c

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
cv_path: cv.html
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1
language_data: data.lang.vi
language_includes_dir: _languages
BASE_PATH: 
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - jekyll-language-plugin
include:
  - "_imgs"
  - "_notebooks"