# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
paginate: 7 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: qsnotepad
google_analytics: UA-68629572-1

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Bryan
      description: notes of a novice
author:
  name: Bryan Nguyễn
  email: quy_nguyen@knorex.com
  bio: Full Stack Over Flow Engineer
  linkedin: hongquy
  github: dongchirua
  facebook: hquy.nguyen
  500px: quynguyen4
  googleplus: +NguyenHongQuydongchirua
  stack: 1432142
  email_md5: 04b4bf7d93ffa782657ac8561f1cbd3c

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
cv_path: cv.html
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:
gems:
  - jekyll-paginate
