# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
safe: true
paginate: 7 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: redcarpet # kramdown
disqus: qsnotepad
google_analytics: UA-68629572-1
url: http://nhquy.com
permalink:           pretty
relative_permalinks: true

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: QsNotepad++

description: My play ground
author:
  name: Hồng Quy
  email: quy@faircare.io
  bio: Data Science Engineer
  linkedin: hongquy
  email_md5: 1f666b3428d24513c8376b9be1463d8c

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
